### ISSUE TITLE
Syntax error or computeSimilarities.js

### ISSUE THREAD

**Issue by kuramayoko10** [anvaka/git-also#2]
When I tried the command on my repo (on random files) it failed with the following error message:
```
C:\Users\myusername\AppData\Roaming\npm\node_modules\git-also\lib\computeSimilarities.js:52
      related.forEach(otherFile => {
                                ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\myusername\AppData\Roaming\npm\node_modules\git-also\git-also.js:2:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by anvaka** [comment]
Thank you for reporting this. I didn't realize I was using new version of javascript syntax. This should be fixed in `v1.0.2`. Just run `npm update -g git-also` and it should work.
